### ISSUE TITLE
if mousemove then ShadowEngineDemo program is hang..

### ISSUE THREAD

**Issue by wizinfantry** [dimsa/ShadowEngine#1]
if GlobalUseGPUCanvas = False then FPS 40
if GlobalUseGPUCanvas = True then FPS 100

---

program ShadowEngineDemo;

uses
  System.StartUpCopy,
  FMX.Types,
  FMX.Forms,
  mainUnit in 'mainUnit.pas' {mainForm},
  uClasses in 'Utils\uClasses.pas',
  uNamedList in 'Utils\uNamedList.pas',
  uDemoGame in 'DemoCode\uDemoGame.pas',
  uDemoEngine in 'DemoCode\uDemoEngine.pas',
  uDemoGameLoader in 'DemoCode\uDemoGameLoader.pas',
  uDemoObjects in 'DemoCode\uDemoObjects.pas',
  uDemoMenu in 'DemoCode\uDemoMenu.pas',
  FMX.IniFile.Android in 'Utils\inifile\FMX.IniFile.Android.pas',
  FMX.IniFile.Apple in 'Utils\inifile\FMX.IniFile.Apple.pas',
  FMX.IniFile in 'Utils\inifile\FMX.IniFile.pas',
  uBannerPanel in 'Utils\uBannerPanel.pas' {$R *.res};

{$R *.res}

begin
 GlobalUseGPUCanvas := True;
  Application.Initialize;
  Application.CreateForm(TmainForm, mainForm);
  Application.Run;

**Comment by dimsa** [comment]
Thank you! Interesting feature! I didn't know about GlobalUseGPUCanvas. I found one more bug with it, that I can't use #13 to break textline for example. Are there 100 fps on Android? It's very good result. I will try it and will try to fix it.

**Comment by wizinfantry** [comment]
---

Win32 DEBUG
if GlobalUseGPUCanvas = False then FPS 40

## if GlobalUseGPUCanvas = True then FPS 100

Android DEBUG (LG-F260S)
if GlobalUseGPUCanvas = False then FPS 20~25

## if GlobalUseGPUCanvas = True then FPS  40~45

**Comment by dimsa** [comment]
Hello! Can you Check if I've fixed this Issue.

Added to .dpr this for default
  // If GlobalUseGPUCanvas true, you've got more fps, but lower font rendering quality
  // and you can not use #13 for linebreak, use sLineBreak instead
  GlobalUseGPUCanvas := True;

And changed uEngine2DThread. Now there is CMinSleep = 2, that regulates time of Render Thread idleness.

**Comment by wizinfantry** [comment]
Wow!!!!! Thanks~~~~~~~ Very Good~~~~
